#!/usr/bin/env python3
"""Emit a C source file embedding a binary as a const uint8_t array.

Usage: embed_binary.py <input_file> <output_c_file> <symbol_name>
"""

import sys


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    src, dst, name = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(src, "rb") as f:
        data = f.read()

    lines = [
        "/* Auto-generated by embed_binary.py - do not edit. */",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"const uint8_t {name}[] = {{",
    ]
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        lines.append(f"    {row},")
    lines.append("};")
    lines.append(f"const size_t {name}_len = {len(data)};")
    lines.append("")

    with open(dst, "w", encoding="ascii") as f:
        f.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
